/**
 * CLI report generator for QMS generation logs.
 * Generates HTML and JSON reports with visualizations and insights.
 */

import { Command } from 'commander';
import { promises as fs } from 'node:fs';
import { join } from 'node:path';
import { loadGenerationLog, listLogFiles } from '../utils';
import { generateAnalysis } from './analysis';
import type { AnalysisResult } from '../types';

async function generateHtmlReport(analysis: AnalysisResult, outputPath: string): Promise<void> {
  const { metadata, summary } = analysis;
  
  const css = `
    body { font-family: Arial, sans-serif; margin: 20px; line-height: 1.6; }
    .header { background: #2c3e50; color: white; padding: 20px; border-radius: 8px; }
    .section { margin: 20px 0; padding: 15px; border: 1px solid #ddd; border-radius: 8px; }
    .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; }
    .stat-card { background: #f8f9fa; padding: 15px; border-radius: 6px; text-align: center; }
    .stat-value { font-size: 2em; font-weight: bold; color: #2c3e50; }
    .stat-label { color: #6c757d; font-size: 0.9em; }
    table { width: 100%; border-collapse: collapse; margin: 10px 0; }
    th, td { padding: 8px; text-align: left; border-bottom: 1px solid #ddd; }
    th { background-color: #f8f9fa; }
    pre { background: #f8f9fa; padding: 10px; border-radius: 4px; overflow-x: auto; }
  `;

  const html = `<!DOCTYPE html>
<html>
<head>
  <title>QMS Generation Log Analysis Report</title>
  <style>${css}</style>
</head>
<body>
  <div class="header">
    <h1>QMS Generation Log Analysis Report</h1>
    <p><strong>System:</strong> ${metadata.system} v${metadata.version}</p>
    <p><strong>Environment:</strong> ${metadata.environment}</p>
    <p><strong>Generated:</strong> ${metadata.generated_at}</p>
    <p><strong>File:</strong> ${analysis.file}</p>
  </div>

  <div class="section">
    <h2>📊 Summary</h2>
    <div class="summary-grid">
      <div class="stat-card">
        <div class="stat-value">${summary.totalRuns}</div>
        <div class="stat-label">Total Runs</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">$${summary.totalCostUsd.toFixed(4)}</div>
        <div class="stat-label">Total Cost (USD)</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">${summary.avgCostUsd.toFixed(4)}</div>
        <div class="stat-label">Avg Cost per Run</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">${summary.totalDurationMs.toLocaleString()}ms</div>
        <div class="stat-label">Total Duration</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">${summary.avgDurationMs.toFixed(2)}ms</div>
        <div class="stat-label">Avg Duration per Run</div>
      </div>
    </div>
  </div>

  <div class="section">
    <h2>🏭 Systems & Providers</h2>
    <table>
      <tr><th>System</th><th>Run Count</th></tr>
      ${Object.entries(summary.providers).map(([p, c]) => `<tr><td>${p}</td><td>${c}</td></tr>`).join('')}
    </table>
  </div>

  <div class="section">
    <h2>📈 Key Metrics</h2>
    <table>
      <tr><th>Metric</th><th>Value</th></tr>
      <tr><td>Cache Hit Rate</td><td>${(summary.cacheHitRate * 100).toFixed(2)}%</td></tr>
      <tr><td>Safety Pass Rate</td><td>${(summary.safetyPassRate * 100).toFixed(2)}%</td></tr>
      <tr><td>Date Range</td><td>${summary.dateRange ? `${summary.dateRange.from} to ${summary.dateRange.to}` : 'N/A'}</td></tr>
    </table>
  </div>

  <div class="section">
    <h2>📋 Step Type Counts</h2>
    <table>
      <tr><th>Step Type</th><th>Count</th></tr>
      ${Object.entries(summary.stepTypeCounts).map(([t, c]) => `<tr><td>${t}</td><td>${c}</td></tr>`).join('')}
    </table>
  </div>

  <div class="section">
    <h2>⚡ Performance Breakdown (Average ms)</h2>
    <table>
      <tr><th>Step Type</th><th>Avg Duration</th></tr>
      ${Object.entries(summary.performanceBreakdown).map(([k, v]) => `<tr><td>${k}</td><td>${v.toFixed(2)}ms</td></tr>`).join('')}
    </table>
  </div>

  <div class="section">
    <h2>💰 Cost Breakdown (Average USD)</h2>
    <table>
      <tr><th>Step Type</th><th>Avg Cost</th></tr>
      ${Object.entries(summary.costBreakdown).map(([k, v]) => `<tr><td>${k}</td><td>$${v.toFixed(4)}</td></tr>`).join('')}
    </table>
  </div>

  <div class="section">
    <h2>🔍 Raw Analysis Data</h2>
    <pre>${JSON.stringify(summary, null, 2)}</pre>
  </div>

  <footer>
    <p>Generated by QMS DevTools Analysis Suite</p>
  </footer>
</body>
</html>
`;

  await fs.writeFile(outputPath, html, 'utf-8');
}

async function main() {
  const program = new Command();
  program
    .name('devtools-report')
    .description('Generate HTML/JSON reports from QMS generation logs')
    .option('-d, --directory <path>', 'Directory containing .devtools files', '.devtools')
    .option('-o, --output <file>', 'Output file path')
    .option('-f, --format <format>', 'Output format (html|json|both)', 'html')
    .option('--title <title>', 'Report title')
    .option('--include <file>', 'Specific file to process (can repeat)', (v, prev) => [...(prev || []), v]);

  program.parse();
  const options = program.opts();

  const directory = options.directory as string;
  const output = options.output as string | undefined;
  const format = options.format as 'html' | 'json' | 'both';
  const title = options.title as string | undefined;
  const includeFiles = (options.include as string[] | undefined) || [];

  try {
    const files = includeFiles.length > 0
      ? includeFiles
      : await listLogFiles(directory);

    console.log(`📄 Processing ${files.length} file(s)...`);

    const analyses = [];
    for (const file of files) {
      try {
        const log = await loadGenerationLog(file);
        const analysis = generateAnalysis(file, log);
        if (title) analysis.metadata.system = title;
        analyses.push(analysis);
      } catch (err) {
        console.error(`⚠️ Failed to process ${file}: ${(err as Error).message}`);
      }
    }

    if (analyses.length === 0) {
      console.error('❌ No analyses generated');
      process.exit(1);
    }

    // Generate JSON report
    if (format === 'json' || format === 'both') {
      const jsonOutput = output?.endsWith('.html') || !output
        ? join(output || 'report', 'report.json')
        : output;
      await fs.mkdir(join(jsonOutput, '..'), { recursive: true });
      await fs.writeFile(jsonOutput, JSON.stringify(analyses, null, 2), 'utf-8');
      console.log(`📄 JSON report written to: ${jsonOutput}`);
    }

    // Generate HTML report
    if (format === 'html' || format === 'both') {
      const htmlOutput = output || 'report.html';
      await fs.mkdir(join(htmlOutput, '..'), { recursive: true });
      
      if (format === 'both' && analyses.length > 1) {
        // Combine analyses into single report
        const combined = analyses[0];
        combined.summary.totalRuns = analyses.reduce((sum, a) => sum + a.summary.totalRuns, 0);
        combined.summary.totalCostUsd = analyses.reduce((sum, a) => sum + a.summary.totalCostUsd, 0);
        combined.summary.totalDurationMs = analyses.reduce((sum, a) => sum + a.summary.totalDurationMs, 0);
        combined.summary.avgCostUsd = combined.summary.totalCostUsd / combined.summary.totalRuns;
        combined.summary.avgDurationMs = combined.summary.totalDurationMs / combined.summary.totalRuns;
        
        await generateHtmlReport(combined, htmlOutput);
      } else {
        await generateHtmlReport(analyses[0], htmlOutput);
      }
      
      console.log(`📄 HTML report written to: ${htmlOutput}`);
    }

    console.log('\n✅ Report generation completed successfully!');

  } catch (err) {
    console.error('❌ Report generation failed:', (err as Error).message);
    process.exit(1);
  }
}

main().catch(err => {
  console.error('❌ Unexpected error:', err);
  process.exit(1);
});